### ISSUE TITLE
clarify relationship between learn and send in example config

### ISSUE THREAD

**Issue by zephyrtronium** [zephyrtronium/robot#78]
Oh, I think I understand what you meant with learn and send

Updating them

```toml
# learn is the tag used to learn Markov chain data from this channel.
learn = 'finleyfisch'
# send is the tag used to generate messages.
send = 'finleyfisch'
```

If this is what you meant, then I might have been confused by the comment

_Originally posted by @seth-rah in https://github.com/zephyrtronium/robot/issues/76#issuecomment-2363926768_
